### ISSUE TITLE
bug: sometimes networks dont show all tools

### ISSUE THREAD

**Issue by Sipke82** [sway2020/FindIt2#77] opened 2020-08-10 18:04 UTC
This bug was also already in the orignal find it.
For example with the surface roads: (https://steamcommunity.com/sharedfiles/filedetails/?id=2175361167&searchtext=surface+roads) 

Sometimes the road tools are gone:

![image](https://user-images.githubusercontent.com/30873812/89815197-a1fa0e80-db44-11ea-9cc8-e131ae8af11e.png)

**Comment by sway2020** [comment] 2020-08-10 20:06
I noticed this issue too when I was working on #75. I know why it does this in the code and I'll try to fix it in the next beta update.

**Comment by sway2020** [comment] 2020-08-11 01:29
@Sipke82 Just a quick update. Do you use Resize It? I'm no longer certain if this is caused by an inherited bug from Find It 1.

**Comment by Sipke82** [comment] 2020-08-11 04:12
Yes I use resize it.

**Comment by sway2020** [comment] 2020-08-16 08:29
I saw Biffa's new video today and he had the "upgrade" icon missing. Probably related to this issue but I don't know the cause yet.

**Comment by sway2020** [comment] 2020-08-22 23:11
Should be fixed in the latest beta update(2.0.3-beta3) along with other related issues with the network options panel. I'll close this issue for now. @Sipke82 Feel free to let me know if it still happens and I'll reopen this issue.

**Closed as completed by sway2020** 2020-08-22 23:11 UTC
Labels: Type: Bug, Status: Completed
